### ISSUE TITLE
get_inches() of Distance is incorrect

### ISSUE THREAD

**Issue by mrmucox** [haydenth/ish_parser#15]
This conversion fails for Distances in METERS and always returns None or 'Missing', and also millimeters convert to inches * 10. I propose the fixes below:

    #This is inches per centimeter:
    INCH_CONVERSION_FACTOR = 1/2.54

    def get_inches(self):
        ''' convert the measurement to inches '''
        if self._obs_value in self.MISSING:
          return 'MISSING'
        if self._obs_units == self.MILLIMETERS:
          return round(self.INCH_CONVERSION_FACTOR * self._obs_value / 10, 4)
        if self._obs_units == self.METERS:
          return round(self.INCH_CONVERSION_FACTOR * self._obs_value * 100, 4)

**Comment by haydenth** [comment]
great! is there anyway you can submit a pull request - im traveling for the
next couple weeks without my computer to make this change!! thanks!!
