### ISSUE TITLE
What does sky cover summation  coverage get numeric return

### ISSUE THREAD

**Issue by danhamill** [haydenth/ish_parser#17]
I have a question about interpreting a reports sky summation cover observation.  If I am looking at the data

```
coverage                                      OVERCAST - 8/8 coverage
secondary_coverage                    Missing
height                                          300
characteristic                               Missing
Name: (1981-01-28 03:22:00+00:00, sky_cover, 1), dtype: object
```

and I use `get_numeric` to convert the coverage data to float

```
a.coverage.get_numeric()
Out[363]: 4.0
```
What does 4.0 mean?  

Thanks for the great package!

**Comment by haydenth** [comment]
hey thanks for the kind words. 4.0 should translate to the table below. if you did it without `get_numeric` does it return `OVERCAST - 8/8 coverage`? It was a cloudy day I guess on 1981-01-28!

```
  CLOUD_TYPES = {
    "0": "Clear - No coverage",
    "1": "FEW - 2/8 or less coverage (not including zero)",
    "2": "SCATTERED - 3/8-4/8 coverage",
    "3": "BROKEN - 5/8-7/8 coverage",
    "4": "OVERCAST - 8/8 coverage",
    "5": "OBSCURED",
    "6": "PARTIALLY OBSCURED",
    "9": "MISSING" }
```

**Comment by haydenth** [comment]
Cool - I guess that worked? :)

**Comment by danhamill** [comment]
Yes, that answered my question.  I am working on a panda's friendly way to access the sky coverage data.  I am thinking of implementing a method in ish_report `.get_pandas_friendly_format()` .. This method would convert the `sky_cover` dictionary to a flat list. 

Once I get a chance to run all of the unittests, I will submit a pr.
