### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by k-nut** [haydenth/ish_parser#5]
Providing a license will make it much easier for other projects to include this nice little library.

**Comment by haydenth** [comment]
oh great idea - thanks. out of curiosity - how are you using this library?

**Comment by k-nut** [comment]
I'm writing my Bachelor Thesis about weather adjustments for energy consumption in buildings and used it to load data that I got from the NOAA's FTP servers. Does that answer your question?

**Comment by haydenth** [comment]
Yeah - cool! Feel free to contribute back or fix any bugs - I wrote this for some simple side projects to parse weather data and am super happy someone else is using it!

Added a license file

**Comment by k-nut** [comment]
ACE! Thank you so much.
